name: recent.lastfm.MooTools
author: thinkphp
current: v1.1
category: Utilities
tags: [lastfm, request, music, media]
docs: https://github.com/thinkphp/recent.lastfm.MooTools/blob/master/docs/recent.lastfm.MooTools.md
demo: http://thinkphp.github.io/recent.lastfm.MooTools/